site_name: Static BI
site_description: "Create Interactive Dashboards from static files"
site_url: 'https://unytics.io/static_bi/'
repo_name: 'unytics/static_bi'
repo_url: 'https://github.com/unytics/static_bi'
edit_uri: 'edit/main'
copyright: 'Copyright &copy; 2025 Unytics'
docs_dir: '..'
site_dir: '../../site'
nav:
  - Get Started: README.md
  - BI Components: docs/bi_components.md
  - Integrations: docs/integrations.md
  - Deployment: docs/deployment.md
theme:
  name: material
  logo: docs/assets/static_bi_logo_dark.svg
  favicon: /assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    - toc.integrate
    - navigation.instant
    - navigation.instant.progress

    # - navigation.path
    # - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    # - navigation.hide
    # - navigation.expand
    - navigation.prune
    # - navigation.sections
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 2
      permalink: "¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search