site_name: Static BI
site_description: "Create Interactive Dashboards from static files"
site_url: 'https://unytics.io/static_bi/'
repo_name: 'unytics/static_bi'
repo_url: 'https://github.com/unytics/static_bi'
edit_uri: 'edit/main'
copyright: 'Copyright &copy; 2025 Unytics'
docs_dir: '..'
site_dir: '../../site'
nav:
  - Get Started: README.md
  - Core Concepts:
    - Motivation: docs/core_concepts/motivation.md
    - Data Sources: docs/core_concepts/data_sources.md
    - BI Components: docs/core_concepts/bi_components.md
    - Cross Filtering: docs/core_concepts/cross_filtering.md
    - Integrations: docs/core_concepts/integrations.md
    - Deployment: docs/core_concepts/deployment.md
  - Data Sources:
    - docs/data_sources/index.md
    - Data Files: docs/data_sources/data_files.md
  - BI Components:
    - docs/ui_components/index.md
    - Score Cards: docs/ui_components/score_cards.md
    - Line Charts: docs/ui_components/line_charts.md
    - Bar Charts: docs/ui_components/bar_charts.md
    - Pie Charts: docs/ui_components/pie_charts.md
    - Data Tables: docs/ui_components/data_tables.md
    - Grids: docs/ui_components/grids.md
  - Integrations:
    - docs/integrations/index.md
    - Mkdocs: docs/integrations/mkdocs.md
    - Docusaurus: docs/integrations/docusaurus.md
    - Shoelace: docs/integrations/docusaurus.md
  - Deployment:
    - docs/deployment/index.md
    - Github pages: docs/deployment/github_pages.md
    - Netlify: docs/deployment/netlify.md
    - Vercel: docs/deployment/vercel.md
    - S3: docs/deployment/s3.md
theme:
  name: material
  logo: docs/assets/static_bi_logo_dark.svg
  favicon: /assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    # - toc.integrate
    - navigation.instant
    - navigation.instant.progress

    # - navigation.path
    # - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    # - navigation.hide
    # - navigation.expand
    - navigation.prune
    # - navigation.sections
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search